### ISSUE TITLE
Lots of errors...

### ISSUE THREAD

**Issue by etnarossolab** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#164]
# Module: 00
#### Step: 00

Description of issue
Errors below returned when creating VM.
-----------------------------------------------------
WARNING: Error occurred when creating storage account for boot diagnostics.  Keep creating a VM with disabling boot diagnostics.  : Microsoft.Rest.ValidationException: 'Kind' cannot be null.
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.Models.StorageAccountCreateParameters.Validate()
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.StorageAccountsOperations.BeginCreateWithHttpMessagesAsync(String resourceGroupName, String accountName, StorageAccountCreateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.StorageAccountsOperations.CreateWithHttpMessagesAsync(String resourceGroupName, String accountName, StorageAccountCreateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.StorageAccountsOperationsExtensions.CreateAsync(IStorageAccountsOperations operations, String resourceGroupName, String accountName, StorageAccountCreateParameters parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.StorageAccountsOperationsExtensions.Create(IStorageAccountsOperations operations, String resourceGroupName, String accountName, StorageAccountCreateParameters parameters)
   at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.CreateStandardStorageAccount(StorageManagementClient client)
Repro steps:

1.
1.
1.

**Comment by etnarossolab** [comment]
embarrassing.
